### ISSUE TITLE
无故报错，导致签到成功后，消息推送的是失败的消息

### ISSUE THREAD

**Issue by DangerFickle** [yunigongshang/GS_GongXueYun#2]
![image](https://github.com/yunigongshang/GS_GongXueYun/assets/59493932/de8118b7-8fde-44cb-8755-59bce1bebff3)

**Comment by yunigongshang** [comment]
> ![image](https://github.com/yunigongshang/GS_GongXueYun/assets/59493932/de8118b7-8fde-44cb-8755-59bce1bebff3)
> 

能看看你配置的.json文件吗

**Comment by yunigongshang** [comment]
> ![image](https://github.com/yunigongshang/GS_GongXueYun/assets/59493932/de8118b7-8fde-44cb-8755-59bce1bebff3)
> 

已经更改，请重新拉取代码，因为更改代码量较小也可查看更改文件自行更改

**Comment by yunigongshang** [comment]
> ![image](https://github.com/yunigongshang/GS_GongXueYun/assets/59493932/de8118b7-8fde-44cb-8755-59bce1bebff3)
> 

已修改，请重新拉取代码，如果未解决问题请继续反映。注意配置文件新增了一项月报开关
