### ISSUE TITLE
建议加入pushplus的推送接口，我这边server酱用不了，每次更新老是去改，怪麻烦的

### ISSUE THREAD

**Issue by DangerFickle** [yunigongshang/GS_GongXueYun#3]

**Comment by yunigongshang** [comment]
> 

我当时写项目的时候pushplus的ip在华为云用不了，我稍后再试一下如果能用我会加上去，能细讲一下server为什么用不了吗

**Comment by DangerFickle** [comment]
可能是我个人设置得不对吧，我也不知道

**Comment by yunigongshang** [comment]
> 可能是我个人设置得不对吧，我也不知道

pushplus推送写好，重新拉一下库，配置文件可以先备份一份
