### ISSUE TITLE
存在封号的风险

### ISSUE THREAD

**Issue by DiyaDe** [yunigongshang/GS_GongXueYun#4]
你好，我发现这个是以前的工学云版本的接口，目前是可以用的，但有封号的风险😣

**Comment by yunigongshang** [comment]
> 你好，我发现这个是以前的工学云版本的接口，目前是可以用的，但有封号的风险😣

目前用了三个月8个账号没有封号情况

**Comment by DiyaDe** [comment]
> > 你好，我发现这个是以前的工学云版本的接口，目前是可以用的，但有封号的风险😣
> 
> 目前用了三个月8个账号没有封号情况

你好，我也有一个跟你一样的仓库，我的是专门跑多用户，大概有100多个，加密以及参数都是一样的但不出意外全给我封了😣

**Comment by muziqiu2** [comment]
> > > 你好，我发现这个是以前的工学云版本的接口，目前是可以用的，但有封号的风险😣
> > 
> > 目前用了三个月8个账号没有封号情况
> 
> 你好，我也有一个跟你一样的仓库，我的是专门跑多用户，大概有100多个，加密以及参数都是一样的但不出意外全给我封了😣

是在服务器上跑的吗？有使用代理IP吗？如果多用户同IP是会被检测到的。

**Comment by DiyaDe** [comment]
> > > > 你好，我发现这个是以前的工学云版本的接口，目前是可以用的，但有封号的风险😣
> > > 
> > > 
> > > 目前用了三个月8个账号没有封号情况
> > 
> > 
> > 你好，我也有一个跟你一样的仓库，我的是专门跑多用户，大概有100多个，加密以及参数都是一样的但不出意外全给我封了😣
> 
> 是在服务器上跑的吗？有使用代理IP吗？如果多用户同IP是会被检测到的。

使用了代理IP的，每个用户的IP是独立的，只是不能保证用户的代理IP保持一直。
